# Zap日志配置
zap:
  prefix: ToDoList
  timeFormat: 2006/01/02 - 15:04:05.00000
  level: info
  caller: true
  stackTrace: true
  encode: json
  # 日志输出到哪里 file | console | both
  writer: file
  logFile:
    maxSize: 20
    backups: 5
    compress: true
    output:
      - "./log/output.log"
    errput:
      - "./log/error.log"

redis:
  enable: true #允许 Redis 缺失时降级
  addr: "192.168.88.130:6379"
  password: "123456"
  db: 0

mysql:
  path: "127.0.0.1"
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db-name: "to_do_list"
  username: "root"
  password: "123456"
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-idle-time: "10m"
  conn-max-lifetime: "60m"